<a href="https://colab.research.google.com/github/shivangirautela/oyesters_training_cum_internship/blob/master/assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [23]:
r=np.random.randint(50,100,10)
r.sort(-1,'mergesort')
r
r[::-1].sort()
r

array([95, 85, 84, 79, 78, 75, 68, 67, 62, 55])

In [24]:
c=7
r=np.append(r,c)
r

array([95, 85, 84, 79, 78, 75, 68, 67, 62, 55,  7])

In [25]:
c=np.power(r,3)
print(c)
sq=np.sqrt(r)
print(sq)

[857375 614125 592704 493039 474552 421875 314432 300763 238328 166375
    343]
[9.74679434 9.21954446 9.16515139 8.88819442 8.83176087 8.66025404
 8.24621125 8.18535277 7.87400787 7.41619849 2.64575131]


In [26]:
s=np.sum(r)
print(s)
ma=np.max(r)
print(ma)
me=np.min(r)
print(me)
mea=np.mean(r)
print(mea)
mead=np.median(r)
print(mead)

755
95
7
68.63636363636364
75.0


In [28]:
n=(r-me)/(ma-me)
n


array([1.        , 0.88636364, 0.875     , 0.81818182, 0.80681818,
       0.77272727, 0.69318182, 0.68181818, 0.625     , 0.54545455,
       0.        ])