<a href="https://colab.research.google.com/github/shivangirautela/oyesters_training_cum_internship/blob/master/Day_2_ML_Webinar%5Bnumpy%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np #alias

In [1]:
import sys    #check version of python
sys.version

'3.6.9 (default, Apr 18 2020, 01:56:04) \n[GCC 8.4.0]'

In [4]:
print(np.__version__)   #version of numpy

1.18.4


In [5]:
#1. create an array
np.array(1)

array(1)

In [0]:
#scalar - 0 dimensional array (only a single)
#vector - 1 dimensional array((1 or n)row/ (1 or n)columns)
#matrix - 2 dimensional array(row * columns)

#scalar array

In [8]:
a= np.array(2)
print(a)  #printing array
print(type(a))
print(a.size)   #values in array
print(a.shape)  #shape
print(a.ndim)    #dimension of array
print(a.dtype)   #datatype

2
<class 'numpy.ndarray'>
1
()
0
int64


In [10]:
a= np.array([1,2,3,4],dtype= 'int32')
print(a)  #printing array
print(type(a))
print(a.size)   #values in array   (attributes)
print(a.shape)  #shape
print(a.ndim)    #dimension of array
print(a.dtype)   #datatype

[1 2 3 4]
<class 'numpy.ndarray'>
4
(4,)
1
int32


In [12]:
#matrix
#vector
a= np.array([[1,2,3],[2,3,4]],dtype= 'int32')
print(a)  #printing array
print(type(a))
print(a.size)   #values in array   (attributes)
print(a.shape)  #shape
print(a.ndim)    #dimension of array
print(a.dtype)   #datatype

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
6
(2, 3)
2
int32


In [15]:
# 3 D array
a= np.array([[[1,2,3],[2,3,4]],[[2,3,6],[7,8,9]]],dtype= 'int32')
print(a)  #printing array
              # (attributes)
print(a.shape)  #shape
print(a.ndim)    #dimension of array

[[[1 2 3]
  [2 3 4]]

 [[2 3 6]
  [7 8 9]]]
(2, 2, 3)
3


In [22]:
#methods
#creatig a random vector
r = np.random.randint(1,100,30)
#lowest value
#highest value
# count
print(r)
r.shape

[70 96  5 13 26 65 52 10 41 48 69 16 27 55 30 87 42 13 39 18 55 56 80 84
 23 54 34 66 10 31]


(30,)

In [23]:
#converting vector into matrix
r.reshape(6,5).astype('float32')

array([[70., 96.,  5., 13., 26.],
       [65., 52., 10., 41., 48.],
       [69., 16., 27., 55., 30.],
       [87., 42., 13., 39., 18.],
       [55., 56., 80., 84., 23.],
       [54., 34., 66., 10., 31.]], dtype=float32)

In [0]:
np.random.randint?  #documentation

In [24]:
2.5 * np.random.random(10)  # 10 random number *2.5

array([0.14465738, 0.70565047, 0.70913637, 2.2572738 , 0.13304082,
       1.6588995 , 1.64156482, 0.27598747, 1.42686125, 1.29191237])

In [25]:
#direct randomn value matrix
r = np.random.randint(1,100,size=(3,4))
r

array([[64, 95, 82, 43],
       [45, 75, 64, 82],
       [ 2, 18, 81, 94]])

In [28]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [31]:
#calculating distance
a=np.array([1,2])
b=np.array([3,4])
d1 = np.linalg.norm(a)
d2=np.linalg.norm(b)
print(d1)
print(d2)
print(np.linalg.norm(a-b))

2.23606797749979
5.0
2.8284271247461903


In [34]:
 np.ones(10,dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
np.ones([5,5])   #white background vision

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
a = range(1,10)
list(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]